version: '2'

services:

  influxdb:
    image: influxdb:1.8-alpine
    ports:
    - "8086:8086"
    volumes:
    - "./influxdb_data:/var/lib/influxdb"
    environment:
    - INFLUXDB_DB=${DATABASE}
    - INFLUXDB_ADMIN_USER=${DATABASE_ADMIN_USER}
    - INFLUXDB_ADMIN_PASSWORD=${DATABASE_ADMIN_PASSWORD}
    - INFLUXDB_USER=${DATABASE_USER}
    - INFLUXDB_USER_PASSWORD=${DATABASE_PASSWORD}
